import type { AnalysisRule, RuleMatch } from '../engine'
import type { FetchedFile } from '@/lib/github/file-fetcher'

export const architectureRules: AnalysisRule[] = [
  {
    id: 'ARCH_001',
    category: 'ARCHITECTURE',
    title: 'God file detected',
    description: 'Your source file has over 500 lines of code. Large files are hard to understand, debug, and maintain. They typically indicate the file is doing too many things (violating single responsibility principle). Changes become risky because you might break unrelated functionality in the same file.',
    severity: 'WARNING',
    suggestion: 'Split large files into smaller modules based on functionality. Aim for files under 200-300 lines. Extract services, utilities, validators, and helpers into separate files.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const sourceFiles = files.filter(
        (f) =>
          /\.(ts|js|tsx|jsx|py|go|rb|java|kt|rs)$/.test(f.path) &&
          !/\.(test|spec|generated|gen|pb)\.(ts|js|tsx|jsx|py)$/.test(f.path) &&
          !/node_modules/.test(f.path) &&
          // Skip Prisma migrations, SQL files, and lock files
          !/\/migrations\//.test(f.path) &&
          !/\.(sql|lock|snap)$/.test(f.path) &&
          // Skip auto-generated files that commonly have a header comment
          !/(auto.?generated|do not edit|generated by)/i.test(f.lines.slice(0, 3).join('\n'))
      )

      for (const file of sourceFiles) {
        if (file.lines.length > 500) {
          matches.push({
            ruleId: 'ARCH_001',
            title: `God file: ${file.path.split('/').pop()} (${file.lines.length} lines)`,
            description: `File has ${file.lines.length} lines — likely violates single responsibility principle.`,
            severity: 'WARNING',
            filePath: file.path,
            evidence: `${file.lines.length} lines of code`,
            suggestion: 'Extract logical sections into separate service, helper, or utility files.',
            category: 'ARCHITECTURE',
          })
          if (matches.length >= 5) return matches
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_002',
    category: 'ARCHITECTURE',
    title: 'Business logic directly in route handlers',
    description: 'Your route files contain database queries and business logic directly. Routes should only handle HTTP (parse request, send response). Business logic in routes makes code hard to test, reuse, and maintain.',
    severity: 'WARNING',
    suggestion: 'Extract business logic into service files. Node.js: services/userService.ts. Python: services/user_service.py or a separate module. Routes should only call services, not query the database directly.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const routeFiles = files.filter(
        (f) => /\/(routes|api|views|routers)\//.test(f.path) && /\.(ts|js|py)$/.test(f.path) && !/\.(test|spec)\./.test(f.path)
      )

      for (const file of routeFiles) {
        const isPy = /\.py$/.test(file.path)
        const hasDirectDbInRoute = isPy
          ? /session\.query|db\.query|cursor\.execute|Model\.objects\.(filter|get|create|update|delete)/.test(file.content) &&
            /@(app|router|bp|blueprint)\.(route|get|post|put|delete|patch)/.test(file.content)
          : (/app\.(get|post|put|delete)\([^,]+,\s*async.*prisma\.|router\.(get|post|put|delete)\([^,]+,\s*async.*prisma\./.test(file.content) ||
             (/prisma\.|Model\.find/.test(file.content) && /router\.(get|post|put|delete)|app\.(get|post|put|delete)/.test(file.content)))

        if (hasDirectDbInRoute) {
          const lineIdx = isPy
            ? file.lines.findIndex((l) => /session\.query|cursor\.execute|\.objects\./.test(l))
            : file.lines.findIndex((l) => /prisma\.|Model\.find/.test(l))
          matches.push({
            ruleId: 'ARCH_002',
            title: 'Business logic in route handler',
            description: 'ORM/DB queries found directly in route files — no service abstraction layer.',
            severity: 'WARNING',
            filePath: file.path,
            lineNumber: lineIdx >= 0 ? lineIdx + 1 : undefined,
            evidence: lineIdx >= 0 ? file.lines[lineIdx].trim().slice(0, 200) : 'ORM call in route',
            suggestion: isPy
              ? 'Create a service module (e.g. services/user_service.py) and call it from route handlers.'
              : 'Create a service layer (e.g. services/userService.ts) and call it from routes.',
            category: 'ARCHITECTURE',
          })
          if (matches.length >= 5) break
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_003',
    category: 'ARCHITECTURE',
    title: 'Only console.log / print for logging',
    description: 'Your code only uses console.log (JS) or print() (Python) for logging. In production these are inadequate: no log levels, no structured output, no log rotation, and logs can\'t be easily searched or filtered.',
    severity: 'INFO',
    suggestion: 'Use a structured logging library. Node.js: winston or pino. Python: Python\'s built-in logging module with structured handlers, or structlog/loguru. These provide log levels, JSON formatting, and production-grade log management.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const packageJson = files.find((f) => /package\.json$/.test(f.path))
      const requirementsTxt = files.find((f) => /requirements.*\.txt$/.test(f.path) || f.path === 'requirements.txt')

      // Node.js check
      if (packageJson) {
        let deps: Record<string, string> = {}
        try {
          const parsed = JSON.parse(packageJson.content)
          deps = { ...parsed.dependencies, ...parsed.devDependencies }
        } catch { /* ignore */ }

        const hasLogger = ['winston', 'pino', 'bunyan', 'log4js', 'signale'].some((l) => l in deps)
        if (hasLogger) return []

        const hasConsoleLog = files.some(
          (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) && !/\.(test|spec)\./.test(f.path) && /console\.log/.test(f.content)
        )
        if (!hasConsoleLog) return []

        return [
          {
            ruleId: 'ARCH_003',
            title: 'No structured logging library',
            description: 'Only console.log used — no structured logging (winston/pino) for production observability.',
            severity: 'INFO',
            filePath: packageJson.path,
            evidence: 'No winston/pino/bunyan in dependencies',
            suggestion: 'Install pino or winston for structured JSON logs with log levels and transports.',
            category: 'ARCHITECTURE',
          },
        ]
      }

      // Python check
      if (requirementsTxt) {
        const content = requirementsTxt.content.toLowerCase()
        const hasLogger = ['structlog', 'loguru', 'python-json-logger'].some((l) => content.includes(l))
        if (hasLogger) return []

        // Check if only print() is used instead of logging module
        const hasPrintOnly = files.some(
          (f) => /\.py$/.test(f.path) && /\bprint\(/.test(f.content) && !/\bimport\s+logging\b|\bfrom\s+logging/.test(f.content)
        )
        if (!hasPrintOnly) return []

        return [
          {
            ruleId: 'ARCH_003',
            title: 'Using print() instead of logging module',
            description: 'Python code uses print() for output instead of the logging module — no log levels or structured output.',
            severity: 'INFO',
            filePath: requirementsTxt.path,
            evidence: 'print() used; no logging library found',
            suggestion: 'Use Python\'s built-in logging module or install loguru/structlog for structured production logs.',
            category: 'ARCHITECTURE',
          },
        ]
      }

      return []
    },
  },

  {
    id: 'ARCH_004',
    category: 'ARCHITECTURE',
    title: 'Mixed async styles in same file',
    description: 'Your code mixes both .then() promise chains and async/await in the same file. This inconsistency makes code harder to read and maintain. Different parts of the file handle errors differently (.catch vs try/catch), which can lead to bugs and confusion.',
    severity: 'INFO',
    suggestion: 'Standardize on async/await throughout your codebase. It\'s more readable, handles errors consistently with try/catch, and is easier to debug. Refactor .then() chains to async/await for consistency.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const sourceFiles = files.filter(
        (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) && !/\.(test|spec)\./.test(f.path)
      )

      for (const file of sourceFiles) {
        const hasThen = /\.then\(/.test(file.content)
        const hasAwait = /\bawait\s/.test(file.content)
        if (hasThen && hasAwait) {
          matches.push({
            ruleId: 'ARCH_004',
            title: 'Mixed async styles',
            description: 'File uses both .then() chains and async/await — inconsistent code style.',
            severity: 'INFO',
            filePath: file.path,
            evidence: 'Both .then() and await found in file',
            suggestion: 'Standardize on async/await for consistency and easier error handling.',
            category: 'ARCHITECTURE',
          })
          if (matches.length >= 5) return matches
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_005',
    category: 'ARCHITECTURE',
    title: 'Circular dependency detected',
    description: 'Two or more files import each other in a cycle. Circular dependencies cause undefined behavior, initialization order bugs, and can crash your app at runtime. They indicate tangled architecture where modules are too tightly coupled.',
    severity: 'WARNING',
    suggestion: 'Break circular dependencies by extracting shared code into a third file. Use dependency inversion: depend on interfaces/types instead of concrete implementations. Node.js tip: move shared types to a types/ directory.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const imports: Record<string, string[]> = {}
      const sourceFiles = files.filter(
        (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) && !/node_modules|\.test\.|\.spec\./.test(f.path)
      )

      // Build import graph
      for (const file of sourceFiles) {
        const fileImports: string[] = []
        for (const line of file.lines) {
          const match = line.match(/(?:import|require)\s*(?:\(?\s*['"])([^'"]+)['"]/)
          if (match && match[1].startsWith('.')) {
            // Resolve relative path
            const parts = file.path.split('/')
            parts.pop()
            const resolved = [...parts, match[1]].join('/').replace(/\/\.\//g, '/')
            fileImports.push(resolved.replace(/\.(ts|js|tsx|jsx)$/, ''))
          }
        }
        imports[file.path.replace(/\.(ts|js|tsx|jsx)$/, '')] = fileImports
      }

      // Detect simple A→B→A cycles
      for (const [fileA, depsA] of Object.entries(imports)) {
        for (const depB of depsA) {
          const depsB = imports[depB]
          if (depsB && depsB.some((d) => fileA.endsWith(d.split('/').pop()!) || d === fileA)) {
            const nameA = fileA.split('/').pop()
            const nameB = depB.split('/').pop()
            matches.push({
              ruleId: 'ARCH_005',
              title: `Circular dependency: ${nameA} ↔ ${nameB}`,
              description: `${nameA} and ${nameB} import each other — circular dependency causes initialization bugs.`,
              severity: 'WARNING',
              filePath: fileA + '.ts',
              evidence: `${nameA} imports ${nameB}, which imports ${nameA}`,
              suggestion: 'Extract shared code to a third module, or use dependency inversion.',
              category: 'ARCHITECTURE',
            })
            if (matches.length >= 3) return matches
          }
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_006',
    category: 'ARCHITECTURE',
    title: 'Configuration hardcoded in source files',
    description: 'Your source files contain hardcoded configuration values (port numbers, URLs, feature flags, limits) instead of reading from config files or environment variables. This makes it impossible to change behavior without code changes and redeployment.',
    severity: 'INFO',
    suggestion: 'Move configuration to environment variables or a config module. Create a central config file (e.g. config.ts) that reads from process.env with defaults. This allows different values per environment without code changes.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const sourceFiles = files.filter(
        (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) &&
        /\/(routes|api|controllers|services|lib)\//.test(f.path) &&
        !/\.(test|spec|config)\./.test(f.path)
      )

      for (const file of sourceFiles) {
        for (let i = 0; i < file.lines.length; i++) {
          const line = file.lines[i]
          // Hardcoded port numbers, timeouts, limits
          if (/\b(port|PORT)\s*[:=]\s*\d{4}\b/.test(line) && !/process\.env|os\.environ/.test(line)) {
            matches.push({
              ruleId: 'ARCH_006',
              title: 'Hardcoded port number in source',
              description: 'Port number hardcoded instead of read from environment — inflexible across environments.',
              severity: 'INFO',
              filePath: file.path,
              lineNumber: i + 1,
              evidence: line.trim().slice(0, 200),
              suggestion: 'Use: const port = process.env.PORT || 3000 to allow environment-specific config.',
              category: 'ARCHITECTURE',
            })
            if (matches.length >= 3) return matches
          }
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_007',
    category: 'ARCHITECTURE',
    title: 'Deeply nested callbacks/conditionals',
    description: 'Your code has deeply nested callback chains or conditional statements (4+ levels of indentation). Deep nesting makes code extremely hard to read, debug, and maintain. It often indicates logic that should be broken into smaller functions.',
    severity: 'INFO',
    suggestion: 'Flatten deep nesting using early returns (guard clauses), Promise.all(), or extracting nested logic into named functions. Replace nested if/else with early returns: if (!condition) return; instead of if (condition) { deeply nested code }.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const sourceFiles = files.filter(
        (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) && !/\.(test|spec)\./.test(f.path)
      )

      for (const file of sourceFiles) {
        for (let i = 0; i < file.lines.length; i++) {
          const line = file.lines[i]
          // Count leading whitespace to detect deep nesting
          const indent = line.match(/^(\s*)/)?.[1].length ?? 0
          const spaces = /\t/.test(line) ? indent * 4 : indent
          // 5+ levels of nesting (20+ spaces or 5+ tabs)
          if (spaces >= 20 && /\b(if|for|while|try|switch|\.then)\b/.test(line)) {
            matches.push({
              ruleId: 'ARCH_007',
              title: 'Deeply nested code (5+ levels)',
              description: `Code nested ${Math.floor(spaces / 4)}+ levels deep — hard to read and maintain.`,
              severity: 'INFO',
              filePath: file.path,
              lineNumber: i + 1,
              evidence: line.trim().slice(0, 200),
              suggestion: 'Use early returns, extract to named functions, or flatten with Promise combinators.',
              category: 'ARCHITECTURE',
            })
            if (matches.length >= 3) return matches
          }
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_008',
    category: 'ARCHITECTURE',
    title: 'TypeScript strict mode not enabled',
    description: 'Your TypeScript configuration does not enable strict mode. Without strict, TypeScript allows implicit any types, nullable access without checks, and other patterns that defeat the purpose of using TypeScript. You get a false sense of type safety.',
    severity: 'WARNING',
    suggestion: 'Enable strict mode in tsconfig.json: "strict": true. This enables strictNullChecks, noImplicitAny, strictFunctionTypes, and other checks that catch real bugs at compile time.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const tsconfig = files.find((f) => /tsconfig\.json$/.test(f.path))
      if (!tsconfig) return []

      try {
        const parsed = JSON.parse(tsconfig.content)
        const strict = parsed?.compilerOptions?.strict
        if (strict === true) return []

        return [
          {
            ruleId: 'ARCH_008',
            title: 'TypeScript strict mode not enabled',
            description: 'tsconfig.json does not have "strict": true — many type errors are silently ignored.',
            severity: 'WARNING',
            filePath: tsconfig.path,
            evidence: `strict: ${strict === undefined ? 'not set' : strict}`,
            suggestion: 'Set "strict": true in compilerOptions for full type safety.',
            category: 'ARCHITECTURE',
          },
        ]
      } catch {
        return []
      }
    },
  },

  {
    id: 'ARCH_009',
    category: 'ARCHITECTURE',
    title: 'Hardcoded magic numbers',
    description: 'Your code contains unexplained numeric literals ("magic numbers") used in business logic. Numbers like 86400, 1000, 30, or 2.5 have no context — future developers (including you) won\'t know what they mean or whether it\'s safe to change them.',
    severity: 'INFO',
    suggestion: 'Extract magic numbers into named constants. const MAX_RETRIES = 3; const CACHE_TTL_SECONDS = 300; const TAX_RATE = 0.08. This documents intent and makes values easy to update in one place.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const matches: RuleMatch[] = []
      const sourceFiles = files.filter(
        (f) => /\.(ts|js|tsx|jsx)$/.test(f.path) &&
        /\/(routes|api|controllers|services|lib)\//.test(f.path) &&
        !/\.(test|spec|config|constants)\./.test(f.path)
      )

      for (const file of sourceFiles) {
        for (let i = 0; i < file.lines.length; i++) {
          const line = file.lines[i]
          // Suspicious magic numbers in business logic (not 0, 1, 2, or common ones)
          if (/(?:===?|!==?|>=?|<=?|[+\-*/])\s*(?:86400|3600|604800|2592000|31536000|1440|525600)\b/.test(line)) {
            matches.push({
              ruleId: 'ARCH_009',
              title: 'Magic time constant (seconds/minutes)',
              description: 'Time-based magic number — hard to understand without a named constant.',
              severity: 'INFO',
              filePath: file.path,
              lineNumber: i + 1,
              evidence: line.trim().slice(0, 200),
              suggestion: 'Extract to: const ONE_DAY_SECONDS = 86400 or const CACHE_TTL = 3600.',
              category: 'ARCHITECTURE',
            })
            if (matches.length >= 3) return matches
          }
        }
      }
      return matches
    },
  },

  {
    id: 'ARCH_010',
    category: 'ARCHITECTURE',
    title: 'No test files detected',
    description: 'Your repository has no test files (.test.ts, .spec.ts, test_*.py, *_test.go). Without tests, you cannot verify that code works correctly, catch regressions during refactoring, or ensure new features don\'t break existing functionality.',
    severity: 'WARNING',
    suggestion: 'Add tests for critical business logic. Node.js: use vitest or jest. Python: use pytest. Go: built-in testing package. Start with tests for your most critical routes and services — even 20% coverage catches major bugs.',
    detect(files: FetchedFile[]): RuleMatch[] {
      const hasTestFiles = files.some(
        (f) =>
          /\.(test|spec)\.(ts|js|tsx|jsx)$/.test(f.path) ||
          /test_\w+\.py$/.test(f.path) ||
          /_test\.go$/.test(f.path) ||
          /\/tests?\//.test(f.path) ||
          /\/__tests__\//.test(f.path)
      )
      if (hasTestFiles) return []

      // Only flag if there is actual source code (not just config)
      const hasSource = files.some(
        (f) => /\.(ts|js|tsx|jsx|py|go)$/.test(f.path) &&
        /\/(routes|api|controllers|services|lib|src|utils)\//.test(f.path)
      )
      if (!hasSource) return []

      return [
        {
          ruleId: 'ARCH_010',
          title: 'No test files detected',
          description: 'Repository has no test files — zero automated test coverage.',
          severity: 'WARNING',
          filePath: 'package.json',
          evidence: 'No .test.ts, .spec.ts, test_*.py, or *_test.go files found',
          suggestion: 'Add tests for critical paths using vitest/jest (JS), pytest (Python), or Go testing.',
          category: 'ARCHITECTURE',
        },
      ]
    },
  },

  {
    id: 'ARCH_011',
    category: 'ARCHITECTURE',
    title: 'Tight coupling to specific database ORM',
    description: 'Your route handlers and business logic import and call the ORM directly (e.g. prisma, sequelize, mongoose) instead of going through a repository or data access layer. This makes it extremely difficult to switch databases, write unit tests, or add cross-cutting concerns like caching.',
    severity: 'INFO',
    suggestion: 'Add a repository/data-access layer between your business logic and ORM. Create files like repositories/userRepository.ts that encapsulate all ORM calls. Services and routes call the repository, not the ORM directly.',
    detect(files: FetchedFile[]): RuleMatch[] {
      // Count files that directly import/use the ORM
      const ormDirectUsage = files.filter(
        (f) =>
          /\.(ts|js|tsx|jsx)$/.test(f.path) &&
          /\/(routes|api|controllers|services)\//.test(f.path) &&
          !/\.(test|spec)\./.test(f.path) &&
          /import.*prisma|require.*prisma|from.*prisma/i.test(f.content)
      )

      if (ormDirectUsage.length >= 5) {
        return [
          {
            ruleId: 'ARCH_011',
            title: 'ORM used directly in many files',
            description: `${ormDirectUsage.length} route/service files import Prisma directly — tightly coupled to the ORM.`,
            severity: 'INFO',
            filePath: ormDirectUsage[0].path,
            evidence: `Prisma imported directly in ${ormDirectUsage.length} files: ${ormDirectUsage.slice(0, 3).map((f) => f.path.split('/').pop()).join(', ')}`,
            suggestion: 'Create a repository layer (e.g. repositories/userRepo.ts) to encapsulate all ORM calls.',
            category: 'ARCHITECTURE',
          },
        ]
      }
      return []
    },
  },

  {
    id: 'ARCH_012',
    category: 'ARCHITECTURE',
    title: 'No API response type definitions',
    description: 'Your API routes return plain objects without TypeScript interfaces or types defining the response shape. Without response types, consumers don\'t know what fields to expect, and refactoring can silently break clients.',
    severity: 'INFO',
    suggestion: 'Define response types for all API endpoints. Create types/api.ts with interfaces like: interface UserResponse { id: string; name: string; email: string }. Use these in your route handlers: res.json<UserResponse>({...}).',
    detect(files: FetchedFile[]): RuleMatch[] {
      const routeFiles = files.filter(
        (f) => /\.(ts|tsx)$/.test(f.path) &&
        /\/(api|routes)\//.test(f.path) &&
        !/\.(test|spec)\./.test(f.path)
      )

      if (routeFiles.length === 0) return []

      // Check if any route file uses typed responses
      const hasTypedResponses = routeFiles.some(
        (f) => /Response<|NextResponse\.json<|res\.json<|: ApiResponse|interface.*Response/.test(f.content)
      )
      if (hasTypedResponses) return []

      // Check if there are type files for API responses
      const hasApiTypes = files.some(
        (f) => /types\/(api|response)|\.d\.ts/.test(f.path) && /Response|ApiResult/.test(f.content)
      )
      if (hasApiTypes) return []

      const routeCount = routeFiles.length
      if (routeCount < 3) return []

      return [
        {
          ruleId: 'ARCH_012',
          title: 'No API response type definitions',
          description: `${routeCount} API routes return untyped responses — response shape is not documented or enforced.`,
          severity: 'INFO',
          filePath: routeFiles[0].path,
          evidence: `${routeCount} route files without typed response interfaces`,
          suggestion: 'Create shared response types in types/api.ts and use them in route handlers.',
          category: 'ARCHITECTURE',
        },
      ]
    },
  },
]
